using Volo.Abp;

namespace SimulationCommunication.EntityFrameworkCore;

public abstract class SimulationCommunicationEntityFrameworkCoreTestBase : SimulationCommunicationTestBase<SimulationCommunicationEntityFrameworkCoreTestModule>
{

}
