using Xunit;

namespace SimulationCommunication.EntityFrameworkCore;

[CollectionDefinition(SimulationCommunicationTestConsts.CollectionDefinitionName)]
public class SimulationCommunicationEntityFrameworkCoreCollection : ICollectionFixture<SimulationCommunicationEntityFrameworkCoreFixture>
{

}
